version: '3.5'

services:
  desafio-web:
    image: ${DOCKER_REGISTRY-}desafio.web
    build:
      context: src/AndreGutierrez.Web/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:80
  desafio-api:
    image: ${DOCKER_REGISTRY-}desafio.api
    depends_on:
    - sqldata
    build:
      context: .
      dockerfile: src/AndreGutierrez.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DEFAULT_CONNECTION=Data Source=sqldata,1433;Initial Catalog=master;Persist Security Info=True;TrustServerCertificate=true;User ID=sa;Password=Stefanini@123
    ports:
      - "5100:80"
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Stefanini@123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
 